apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-xb2x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-xb2x
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-xb2x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-xb2x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-xb2x
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-xb2x@sha256:f478014abdd01e3b30640e921265edc4c67b68d7600e12f7dc5f88dd86f7d0b9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
